INSERT INTO user (email, first_name, last_name)
VALUES
('user0@mail.com','FirstName0','LastName0'),
('user1@mail.com','FirstName1','LastName1'),
('user2@mail.com','FirstName2','LastName2'),
('user3@mail.com','FirstName3','LastName3'),
('user4@mail.com','FirstName4','LastName4'),
('user5@mail.com','FirstName5','LastName5'),
('user6@mail.com','FirstName6','LastName6'),
('user7@mail.com','FirstName7','LastName7'),
('user8@mail.com','FirstName8','LastName8'),
('user9@mail.com','FirstName9','LastName9');


INSERT INTO loan (total, user_id)
VALUES
(37722,(SELECT user_id FROM user ORDER BY RAND()  LIMIT 1)),
(81314,(SELECT user_id FROM user ORDER BY RAND()  LIMIT 1)),
(78428,(SELECT user_id FROM user ORDER BY RAND()  LIMIT 1)),
(38230,(SELECT user_id FROM user ORDER BY RAND()  LIMIT 1)),
(4810,(SELECT user_id FROM user ORDER BY RAND()  LIMIT 1)),
(77014,(SELECT user_id FROM user ORDER BY RAND()  LIMIT 1)),
(6942,(SELECT user_id FROM user ORDER BY RAND()  LIMIT 1)),
(50161,(SELECT user_id FROM user ORDER BY RAND()  LIMIT 1)),
(87670,(SELECT user_id FROM user ORDER BY RAND()  LIMIT 1)),
(79395,(SELECT user_id FROM user ORDER BY RAND()  LIMIT 1)),
(76639,(SELECT user_id FROM user ORDER BY RAND()  LIMIT 1)),
(66976,(SELECT user_id FROM user ORDER BY RAND()  LIMIT 1)),
(8976,(SELECT user_id FROM user ORDER BY RAND()  LIMIT 1)),
(47612,(SELECT user_id FROM user ORDER BY RAND()  LIMIT 1)),
(2985,(SELECT user_id FROM user ORDER BY RAND()  LIMIT 1)),
(4328,(SELECT user_id FROM user ORDER BY RAND()  LIMIT 1)),
(53805,(SELECT user_id FROM user ORDER BY RAND()  LIMIT 1)),
(86206,(SELECT user_id FROM user ORDER BY RAND()  LIMIT 1)),
(5363,(SELECT user_id FROM user ORDER BY RAND()  LIMIT 1)),
(59798,(SELECT user_id FROM user ORDER BY RAND()  LIMIT 1)),
(21664,(SELECT user_id FROM user ORDER BY RAND()  LIMIT 1)),
(76169,(SELECT user_id FROM user ORDER BY RAND()  LIMIT 1)),
(76218,(SELECT user_id FROM user ORDER BY RAND()  LIMIT 1)),
(30488,(SELECT user_id FROM user ORDER BY RAND()  LIMIT 1)),
(80848,(SELECT user_id FROM user ORDER BY RAND()  LIMIT 1)),
(51835,(SELECT user_id FROM user ORDER BY RAND()  LIMIT 1)),
(88410,(SELECT user_id FROM user ORDER BY RAND()  LIMIT 1)),
(54178,(SELECT user_id FROM user ORDER BY RAND()  LIMIT 1)),
(99782,(SELECT user_id FROM user ORDER BY RAND()  LIMIT 1)),
(10035,(SELECT user_id FROM user ORDER BY RAND()  LIMIT 1)),
(34844,(SELECT user_id FROM user ORDER BY RAND()  LIMIT 1)),
(13246,(SELECT user_id FROM user ORDER BY RAND()  LIMIT 1)),
(32452,(SELECT user_id FROM user ORDER BY RAND()  LIMIT 1)),
(89014,(SELECT user_id FROM user ORDER BY RAND()  LIMIT 1)),
(16766,(SELECT user_id FROM user ORDER BY RAND()  LIMIT 1)),
(42943,(SELECT user_id FROM user ORDER BY RAND()  LIMIT 1)),
(80536,(SELECT user_id FROM user ORDER BY RAND()  LIMIT 1)),
(74019,(SELECT user_id FROM user ORDER BY RAND()  LIMIT 1)),
(43753,(SELECT user_id FROM user ORDER BY RAND()  LIMIT 1)),
(7496,(SELECT user_id FROM user ORDER BY RAND()  LIMIT 1)),
(64929,(SELECT user_id FROM user ORDER BY RAND()  LIMIT 1)),
(67870,(SELECT user_id FROM user ORDER BY RAND()  LIMIT 1)),
(99470,(SELECT user_id FROM user ORDER BY RAND()  LIMIT 1)),
(57835,(SELECT user_id FROM user ORDER BY RAND()  LIMIT 1)),
(58493,(SELECT user_id FROM user ORDER BY RAND()  LIMIT 1)),
(79772,(SELECT user_id FROM user ORDER BY RAND()  LIMIT 1)),
(6916,(SELECT user_id FROM user ORDER BY RAND()  LIMIT 1)),
(6019,(SELECT user_id FROM user ORDER BY RAND()  LIMIT 1)),
(17112,(SELECT user_id FROM user ORDER BY RAND()  LIMIT 1)),
(86872,(SELECT user_id FROM user ORDER BY RAND()  LIMIT 1)),
(77891,(SELECT user_id FROM user ORDER BY RAND()  LIMIT 1)),
(70772,(SELECT user_id FROM user ORDER BY RAND()  LIMIT 1)),
(83616,(SELECT user_id FROM user ORDER BY RAND()  LIMIT 1)),
(10363,(SELECT user_id FROM user ORDER BY RAND()  LIMIT 1)),
(8631,(SELECT user_id FROM user ORDER BY RAND()  LIMIT 1)),
(75146,(SELECT user_id FROM user ORDER BY RAND()  LIMIT 1)),
(45011,(SELECT user_id FROM user ORDER BY RAND()  LIMIT 1)),
(63650,(SELECT user_id FROM user ORDER BY RAND()  LIMIT 1)),
(97219,(SELECT user_id FROM user ORDER BY RAND()  LIMIT 1)),
(12541,(SELECT user_id FROM user ORDER BY RAND()  LIMIT 1)),
(78066,(SELECT user_id FROM user ORDER BY RAND()  LIMIT 1)),
(54297,(SELECT user_id FROM user ORDER BY RAND()  LIMIT 1)),
(52816,(SELECT user_id FROM user ORDER BY RAND()  LIMIT 1)),
(33433,(SELECT user_id FROM user ORDER BY RAND()  LIMIT 1)),
(31439,(SELECT user_id FROM user ORDER BY RAND()  LIMIT 1)),
(51230,(SELECT user_id FROM user ORDER BY RAND()  LIMIT 1)),
(31198,(SELECT user_id FROM user ORDER BY RAND()  LIMIT 1)),
(18189,(SELECT user_id FROM user ORDER BY RAND()  LIMIT 1)),
(43649,(SELECT user_id FROM user ORDER BY RAND()  LIMIT 1)),
(5819,(SELECT user_id FROM user ORDER BY RAND()  LIMIT 1)),
(68547,(SELECT user_id FROM user ORDER BY RAND()  LIMIT 1)),
(64494,(SELECT user_id FROM user ORDER BY RAND()  LIMIT 1)),
(48875,(SELECT user_id FROM user ORDER BY RAND()  LIMIT 1)),
(12974,(SELECT user_id FROM user ORDER BY RAND()  LIMIT 1)),
(41151,(SELECT user_id FROM user ORDER BY RAND()  LIMIT 1)),
(22552,(SELECT user_id FROM user ORDER BY RAND()  LIMIT 1)),
(36380,(SELECT user_id FROM user ORDER BY RAND()  LIMIT 1)),
(83148,(SELECT user_id FROM user ORDER BY RAND()  LIMIT 1)),
(31699,(SELECT user_id FROM user ORDER BY RAND()  LIMIT 1)),
(80485,(SELECT user_id FROM user ORDER BY RAND()  LIMIT 1)),
(93139,(SELECT user_id FROM user ORDER BY RAND()  LIMIT 1)),
(98684,(SELECT user_id FROM user ORDER BY RAND()  LIMIT 1)),
(78625,(SELECT user_id FROM user ORDER BY RAND()  LIMIT 1)),
(72839,(SELECT user_id FROM user ORDER BY RAND()  LIMIT 1)),
(88499,(SELECT user_id FROM user ORDER BY RAND()  LIMIT 1)),
(91977,(SELECT user_id FROM user ORDER BY RAND()  LIMIT 1)),
(44151,(SELECT user_id FROM user ORDER BY RAND()  LIMIT 1)),
(23085,(SELECT user_id FROM user ORDER BY RAND()  LIMIT 1)),
(14144,(SELECT user_id FROM user ORDER BY RAND()  LIMIT 1)),
(87338,(SELECT user_id FROM user ORDER BY RAND()  LIMIT 1)),
(51748,(SELECT user_id FROM user ORDER BY RAND()  LIMIT 1)),
(31798,(SELECT user_id FROM user ORDER BY RAND()  LIMIT 1)),
(64733,(SELECT user_id FROM user ORDER BY RAND()  LIMIT 1)),
(20765,(SELECT user_id FROM user ORDER BY RAND()  LIMIT 1)),
(88867,(SELECT user_id FROM user ORDER BY RAND()  LIMIT 1)),
(4376,(SELECT user_id FROM user ORDER BY RAND()  LIMIT 1)),
(88287,(SELECT user_id FROM user ORDER BY RAND()  LIMIT 1)),
(23994,(SELECT user_id FROM user ORDER BY RAND()  LIMIT 1)),
(75854,(SELECT user_id FROM user ORDER BY RAND()  LIMIT 1)),
(9450,(SELECT user_id FROM user ORDER BY RAND()  LIMIT 1)),
(62418,(SELECT user_id FROM user ORDER BY RAND()  LIMIT 1)),
(51343,(SELECT user_id FROM user ORDER BY RAND()  LIMIT 1)),
(77802,(SELECT user_id FROM user ORDER BY RAND()  LIMIT 1)),
(54311,(SELECT user_id FROM user ORDER BY RAND()  LIMIT 1)),
(36593,(SELECT user_id FROM user ORDER BY RAND()  LIMIT 1)),
(39631,(SELECT user_id FROM user ORDER BY RAND()  LIMIT 1)),
(1100,(SELECT user_id FROM user ORDER BY RAND()  LIMIT 1)),
(56781,(SELECT user_id FROM user ORDER BY RAND()  LIMIT 1)),
(26484,(SELECT user_id FROM user ORDER BY RAND()  LIMIT 1)),
(42754,(SELECT user_id FROM user ORDER BY RAND()  LIMIT 1));
